trivial: actually include the empty yield placeholder
fixing the following build failure:

In function `init':
/usr/share/gnoduino/hardware/arduino/cores/arduino/wiring.c:228: undefined reference to `yield'
collect2: error: ld returned 1 exit status

original commit introducing yield in master:
6ecb174c40fb880ac555182f918048b0050b3c98